### ISSUE TITLE
public release?

### ISSUE THREAD

**Issue by afeld** [starkandwayne/airmarshal#1]
Hello! I just watched @mkb's [talk](https://www.youtube.com/watch?v=iAW4yGbKFRk&index=61&list=WL) from Cloud Foundry summit, and Air Marshal seems promising. I'm seeing the [concourse](https://github.com/starkandwayne/airmarshal-concourse) and [boshrelease](https://github.com/starkandwayne/airmarshal-boshrelease) repositories for Air Marshal, but this one is empty. I didn't dig too deeply...is all of the relevant code in those repositories, or is the project still not "released"?

Thanks!

/cc @mogul

**Comment by mkb** [comment]
Thanks for asking! We've done a couple of internal prototypes but don't
have anything releasable yet.

--mkb

**Comment by mkb** [comment]
Since we're not actively working on Air Marshal right now we are killing the repos to avoid confusion and keep our GitHub org tidy.
